variables:
  repository: 'unrealSlim'
  dockerfilePath: '$(Build.SourcesDirectory)/app/Dockerfile'
  tag: '$(Build.BuildId)'

pool:
  vmImage: ubuntu-latest
steps:

  - script:  docker pull ghcr.io/epicgames/unreal-engine:dev-slim-5.0.3
    displayName: 'Docker Pull'
    #condition: ne(variables.CACHE_RESTORED, 'false')

  - script: |
      cat /usr/local/share/ueinstalled && exit
      docker run --rm -d --name ue5 "ghcr.io/epicgames/unreal-engine:dev-slim-5.0.3" bash -c "sleep infinity"
      docker cp "ue5:/home/ue5/UnrealEngine" "/destination/path/on/host/filesystem"
      docker stop ue5
      echo "OK" > /usr/local/share/ueinstalled