name: Unreal Engine 5.3 stable release builder

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.5.1
    - name: Git Clone UE5 release branch
      uses: actions/checkout@master
      with:
        repository: EpicGames/UnrealEngine -b release
        token: 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
        ref: refs/heads/release
    - name: Package an executable file
      run: |
        cd UnrealEngine
        Setup.sh
        GenerateProjectFiles.sh
        make
