name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone UE5 latest stable version
    - uses: actions/checkout@v3
    - name: Git Clone Action
      # You may pin to the exact commit or the version.
      # uses: sudosubin/git-clone-action@8a93ce24d47782e30077508cccacf8a05a891bae
      uses: sudosubin/git-clone-action@v1.0.1
      with:
        # Repository owner and name. Ex: sudosubin/git-clone-action
        repository: EpicGames/UnrealEngine -b release
        # Git branch or tag to checkout.
        ref: refs/heads/release
    - name: Package an executable file
      run: |
        cd UnrealEngine
        Setup.sh
        GenerateProjectFiles.sh
        make
