name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone UE5 latest stable version
      uses: actions/checkout@v3
    - name: Git Clone Action
      uses: sudosubin/git-clone-action@v1.0.1
      with:
        repository: EpicGames/UnrealEngine -b release
        ref: refs/heads/release
    - name: Package an executable file
      run: |
        cd UnrealEngine
        Setup.sh
        GenerateProjectFiles.sh
        make
