name: Unreal Engine 5.3 stable release builder

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.5.1
    - name: Git Clone UE5 release branch
      uses: actions/checkout@v3
      with:
        repository: EpicGames/UnrealEngine
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Package an executable file
      run: |
        cd UnrealEngine
        Setup.sh
        GenerateProjectFiles.sh
        make
